### PHARM-1 Query from Quentin specifying ondemand
POST https://sct-form.hcuge.ch/sharedtreatmentplan/services/cmpd/pharm1 HTTP/1.1
Content-Type: application/soap+xml

< ./pharm1_fml_query.xml

### PHARM-1 Query no doc entry (returns error)
POST https://sct-form.hcuge.ch/sharedtreatmentplan/services/cmpd/pharm1 HTTP/1.1
Content-Type: application/soap+xml

< ./pharm1_fml_query_ondemand.xml

### PHARM-1 Query all (on demand and stable)
POST https://sct-form.hcuge.ch/sharedtreatmentplan/services/cmpd/pharm1 HTTP/1.1
Content-Type: application/soap+xml

< ./pharm1_fml_query_all.xml


### PHARM-1 Query all with no security
POST https://sct-form.hcuge.ch/sharedtreatmentplan/services/cmpd/pharm1 HTTP/1.1
Content-Type: application/soap+xml

< ./pharm1_fml_query_all_nosecurity.xml

###